apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-backend
  namespace: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express-backend
  template:
    metadata:
      labels:
        app: express-backend
    spec:
      containers:
      - name: express-backend
        image: prajyot7/todo-app-backend:latest
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URI
          value: mongodb://mongo:password@mongodb:27017/todo-app?authSource=admin
        - name: CLIENT_URL
          value: http://your-domain.com:8000
