version: '3.8'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/todo-app
      - CLIENT_URL=http://localhost:5173
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    container_name: frontend
    environment:
      - VITE_SERVER_URL=http://localhost:5000/api/todos
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo-data:
